import type { Metadata } from 'next';
import Script from 'next/script';
import '@/style/global.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Script src='/fonts/iconfont.js' strategy='afterInteractive'></Script>
      <body>{children}</body>
    </html>
  );
}
